// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for Supabase configuration
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://kuuulgjkgyhgzkjyembj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1dXVsZ2prZ3loZ3pranllbWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODI2NDYsImV4cCI6MjA2MTU1ODY0Nn0.TAXvtH7t3LEUZH4_DAZtIs9HM17aeXHUJTGHSNRW9bY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);